name: Node.js CI

on:
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '17.x'
            - name: Install dependencies
              run: cd dev/app
              run: npm install
            - run: cd dev/app
              run: npm run build --if-present
            - name: Run tests
              run: cd dev/app
              run: npm test
